[bootstrap.packages]
"brew:bat" = "latest"
"brew:eza" = "latest"
"brew:fd" = "latest"
"brew:fzf" = "latest"
"brew:gh" = "latest"
"brew:ghq" = "latest"
"brew:git" = "latest"
"brew:jq" = "latest"
"brew:mise" = "latest"
"brew:ripgrep" = "latest"
"brew:starship" = "latest"
"brew:zoxide" = "latest"

[bootstrap.repos]
"~/.dotfiles" = { url = "https://github.com/takeyaqa/dotfiles.git" }

[dotfiles]
"~/.zshenv" = {}
"~/.config/gh" = {}
"~/.config/git" = {}
"~/.config/mise" = {}
"~/.config/npm" = {}
"~/.config/zsh" = {}
"~/.config/starship.toml" = {}

[tools]
go = "latest"
java = "temurin-25"
node = "24"
python = "3.14"
ruby = "4"
rust = "latest"

[settings.ruby]
compile = false
